#!/bin/python

# This is just a script I am trying out; Not final!
# It's purpose is to fix the "regular" vulnerabilities in Linux (things like enable firwall, disabling root, removing malware)
# This script is for the use of Team Dragon ONLY
import os
os.system("sudo ufw enable")
os.system("sudo ufw deny telnet")
os.system("sudo ufw deny ftp")

os.system("sudo apt-get purge samba")
os.system("sudo apt-get purge john")
os.system("sudo apt-get purge ftp")
os.system("sudo apt0get purge telnet")

os.system("apt-get install synaptic")
os.system("sudo synaptic")
# Search for malware here and uncheck the boxes
# Examples:netcat, rainbowcrack, telnet, ftp, vnc, etc.

os.system("sudo nano /etc/ssh/sshd_config")
# Set PermitRootLogin to no

os.system("sudo nano /etc/lightdm/lightdm.conf")
# Remove line with autologin-user
# Add the line: allow_guest=false

os.system("sudo apt-get install libpam.cracklib")
os.system("sudo nano /etc/pam.d/common-password")
# At end of pam_unix.so line; remember=5
# At end of pam_cracklib.so line; ucredit=1; lcredit=1; dcredit=1; ocredit=1

