#!/bin/bash
#(Ctrl+Alt+T)to access terminal
#This script is designed to take care of common vulnerabilities on Ubuntu 14 and is for the use of Team Dragon Cyberpatriot
#	Update utilities
#	Find media files
#	Disable permit root login
#	enable firewall
#	disable guest
#	Set firewall port rules
#	Remove bad services
#	List listening processes
#	Secure root password
#	Set password policy
#	Set automatic updating
#	Scans for viruses
#	Activates tcp syn cookie protection

{
echo "<ENABLE SYN COOKIES + DISABLE IPv6>"
	echo "<START>"
 sed -i 's/net.ipv4.tcp_syncookies=0/net.ipv4.tcp_syncookies=1/g' /etc/sysctl.conf

 sed -i 's/net.ipv6.conf.all.disable_ipv6=0/net.ipv6.conf.all.disable_ipv6=1/g' /etc/sysctl.conf
	echo "<END>"
}

{
echo "<DISABLE IP FORWARDING>"
	echo "<START>"
sudo echo 0 > /proc/sys/net/ipv4/ip_forward
	echo "<END>"
}

{
echo "<PREVENT IP SPOOFING>"
	echo "<START>"
sudo echo "nospoof on" >> /etc/host.conf
	echo "<END>"
}

{
echo "<UPDATE UTILITIES>"
	echo "<START>"
apt-get purge firefox --force-yes -y
apt-get purge libreoffice --force-yes -y
apt-get purge ssh --force -yes -y
sudo apt-get update
apt-get install firefox --force-yes -y
apt-get install libreoffice --force-yes -y
apt-get install ssh --force-yes -y
	echo "<END>"
}

{
echo "<VIRUS SCAN>"
	echo "<START>"
sudo apt-get install clamav
sudo freshclam
sudo apt-get install lynis
sudo lynis --check-all
sudo apt-get install chkrootkit
sudo chkrootkit
sudo apt-get install rkhunter
	echo "<END>"
}

{
echo "<PERMIT ROOT LOGIN>"
	echo "<START>"
if [[ -f /etc/ssh/sshd_config ]]; then
        sed -i 's/PermitRootLogin .*/PermitRootLogin no/g' /etc/ssh/sshd_config
    else
        sudo apt-get install ssh --force-yes -y
	sed -i 's/PermitRootLogin .*/PermitRootLogin no/g' /etc/ssh/sshd_config
    fi
	echo "<END>"
}

{
echo "<PERMIT EMPTY PASSWORDS>"
	echo "<START>"
if [[ -f /etc/ssh/sshd_config ]]; then
        sed -i 's/PermitEmptyPasswords .*/PermitEmptyPasswords no/g' /etc/ssh/sshd_config
    else
        sudo apt-get install ssh --force-yes -y
	sed -i 's/PermitEmptyPasswords .*/PermitEmptyPasswords no/g' /etc/ssh/sshd_config
    fi
	echo "<END>"
}

{
echo "<ENABLE FIREWALL>"
	echo "<START>"
sudo ufw enable
	echo "<END>"
}

{
echo "<DISABLE GUEST>"
	echo "<START>"
  sed -i '/autologin_user/d' /etc/lightdm/lightdm.conf
  sed -i 's/allow-guest = true/allow-guest = false/g' /etc/lightdm/lightdm.conf
  sed -i 's/allow-guest = /allow-guest = false/g' /etc/lightdm/lightdm.conf
	echo "<END>"
}

{
echo "<FIREWALL PORT RULES>"
	echo "<START>"
  sudo ufw allow ssh
  sudo ufw deny telnet
  sudo ufw deny ftp
	echo "<END>"
}

{
echo "<REMOVE AND STOP BAD SERVICES>"
	echo "<START>"
  sudo apt-get purge telnet
  sudo apt-get purge john
  sudo apt-get purge ftp
  sudo apt-get purge wireshark
  sudo apt-get purge nmap
  sudo apt-get purge samba
  sudo apt-get purge ophcrack
  sudo apt-get purge hydra
  sudo apt-get purge keylogger
  sudo apt-get install synaptic
  sudo apt-get install bum
  sudo service cups stop
  sudo service vsftp stop
  sudo service postfix stop
  sudo service mysql stop
  sudo service apache2 stop
       echo "<END>"
}

{
echo "<PASSWORD POLICY>"
	echo "<START>"
sudo apt-get install libpam-cracklib --force-yes -y
sed -i.bak -e 's/PASS_MAX_DAYS\t[[:digit:]]\+/PASS_MAX_DAYS\t90/' /etc/login.defs
    	sed -i -e 's/PASS_MIN_DAYS\t[[:digit:]]\+/PASS_MIN_DAYS\t10/' /etc/login.defs
    	sed -i -e 's/PASS_WARN_AGE\t[[:digit:]]\+/PASS_WARN_AGE\t7/' /etc/login.defs
	echo "<END>"
}

{
echo "<AUTOMATIC UPDATING>"
	echo "<START>"
sed -i 's/APT::Periodic::Update-Package-Lists "0";/APT::Periodic::Update-Package-Lists "1";/g' /etc/apt/apt.conf.d/10periodic
	echo "<END>"
}

{
echo "<MEDIA FILES>"
	echo "<START>"
	find /home/ | egrep -e ".*.(jpg|tif|png|gif|wav|mp3|ogg|flac|wma|aac|m4a|flv|webm|ogv|gif|gifv|avi|wmv|mp4|mpg|3gp)"
	echo "<END>"
}

{
echo "<LISTENING PROCESSES>"
#Look for things like apache, telnet, ftp
	echo "<START>"
  sudo netstat -tulnp
	echo "<END>"
}

{
echo "<SECURE ROOT PASSWORD>"
	echo "<START>"
  sudo passwd
#Enter password here
	echo "<END>"
}
